DELETE {{url}}/todo-detail/13
Accept: application/json

###
PATCH {{url}}/todo-detail/13
Content-Type: application/json

{
  "desc": "The than one hand throw always sail none late youth.",
  "img_url": "http://www.forwardsystems.name/solutions/viral"
}

###
POST {{url}}/todo-detail
Content-Type: application/json

{
  "desc": "The than one hand throw always sail none late youth.",
  "img_url": "http://www.forwardsystems.name/solutions/viral",
  "todo_id": 13
}


###
GET {{url}}/todo-detail?id=1,2,3
Accept: application/json

###

GET {{url}}/todo-detail
Accept: application/json

###

GET {{url}}/todo-detail/1
Accept: application/json

###
