DELETE {{url}}/todo/11
Accept: application/json

###
PATCH {{url}}/todo/13
Content-Type: application/json

{
  "amount": 10.5,
  "category_id": null,
  "content": "This is a todo item",
  "deadline": 1717241699200,
  "priority": "HIGH",
  "score": 75,
  "status": "PENDING",
  "title": "Important Task"
}

###
POST {{url}}/todo
Content-Type: application/json

{
  "amount": 10.5,
  "category_id": null,
  "content": "This is a todo item",
  "deadline": 1717241699200,
  "priority": "HIGH",
  "score": 75,
  "status": "PENDING",
  "title": "Important Task"
}


###
GET {{url}}/todo?id=1,2,3
Accept: application/json

###

GET {{url}}/todo
Accept: application/json

###

GET {{url}}/todo/1
Accept: application/json

###
