DELETE {{url}}/todo-tag/52
Accept: application/json

###
PATCH {{url}}/todo-tag/52
Content-Type: application/json

{
  "name": "AnxiousSardine1",
  "todo_id": 2
}

###
POST {{url}}/todo-tag
Content-Type: application/json

{
  "name": "AnxiousSardine1",
  "todo_id": 1
}


###
GET {{url}}/todo-tag?id=1,2,3
Accept: application/json

###

GET {{url}}/todo-tag
Accept: application/json

###

GET {{url}}/todo-tag/1
Accept: application/json

###
