// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: group.sql

package mysqlDao

import (
	"context"
	"database/sql"
	"strings"
)

const CountGroups = `-- name: CountGroups :one
SELECT count(*)
FROM ` + "`" + `group` + "`" + `
`

func (q *Queries) CountGroups(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.countGroupsStmt, CountGroups)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CreateGroup = `-- name: CreateGroup :execresult
INSERT INTO ` + "`" + `group` + "`" + ` (` + "`" + `desc` + "`" + `, ` + "`" + `name` + "`" + `)
VALUES (?, ?)
`

type CreateGroupParams struct {
	Desc string `db:"desc" json:"desc"`
	Name string `db:"name" json:"name"`
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (sql.Result, error) {
	return q.exec(ctx, q.createGroupStmt, CreateGroup, arg.Desc, arg.Name)
}

const DeleteGroup = `-- name: DeleteGroup :exec
DELETE
FROM ` + "`" + `group` + "`" + `
WHERE id = ?
`

func (q *Queries) DeleteGroup(ctx context.Context, id int) error {
	_, err := q.exec(ctx, q.deleteGroupStmt, DeleteGroup, id)
	return err
}

const GetGroup = `-- name: GetGroup :one
SELECT id, name, ` + "`" + `desc` + "`" + `
FROM ` + "`" + `group` + "`" + `
WHERE id = ? LIMIT 1
`

func (q *Queries) GetGroup(ctx context.Context, id int) (Group, error) {
	row := q.queryRow(ctx, q.getGroupStmt, GetGroup, id)
	var i Group
	err := row.Scan(&i.ID, &i.Name, &i.Desc)
	return i, err
}

const GetGroups = `-- name: GetGroups :many
SELECT id, name, ` + "`" + `desc` + "`" + `
FROM ` + "`" + `group` + "`" + `
`

func (q *Queries) GetGroups(ctx context.Context) ([]Group, error) {
	rows, err := q.query(ctx, q.getGroupsStmt, GetGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Group
	for rows.Next() {
		var i Group
		if err := rows.Scan(&i.ID, &i.Name, &i.Desc); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetGroupsByIDs = `-- name: GetGroupsByIDs :many
SELECT id, name, ` + "`" + `desc` + "`" + `
FROM ` + "`" + `group` + "`" + `
WHERE id IN (/*SLICE:ids*/?)
`

func (q *Queries) GetGroupsByIDs(ctx context.Context, ids []int) ([]Group, error) {
	query := GetGroupsByIDs
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.query(ctx, nil, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Group
	for rows.Next() {
		var i Group
		if err := rows.Scan(&i.ID, &i.Name, &i.Desc); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateGroup = `-- name: UpdateGroup :exec
UPDATE ` + "`" + `group` + "`" + `
SET ` + "`" + `desc` + "`" + ` = CASE WHEN ? IS NOT NULL THEN ? ELSE ` + "`" + `desc` + "`" + ` END,
    ` + "`" + `name` + "`" + ` = CASE WHEN ? IS NOT NULL THEN ? ELSE ` + "`" + `name` + "`" + ` END
WHERE id = ?
`

type UpdateGroupParams struct {
	Desc string `db:"desc" json:"desc"`
	Name string `db:"name" json:"name"`
	ID   int    `db:"id" json:"id"`
}

func (q *Queries) UpdateGroup(ctx context.Context, arg UpdateGroupParams) error {
	_, err := q.exec(ctx, q.updateGroupStmt, UpdateGroup,
		arg.Desc,
		arg.Desc,
		arg.Name,
		arg.Name,
		arg.ID,
	)
	return err
}
