// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package mysqlDao

import (
	"database/sql"
)

type GoadminMenu struct {
	ID         uint32         `db:"id" json:"id"`
	ParentID   uint32         `db:"parent_id" json:"parent_id"`
	Type       uint32         `db:"type" json:"type"`
	Order      uint32         `db:"order" json:"order"`
	Title      string         `db:"title" json:"title"`
	Icon       string         `db:"icon" json:"icon"`
	Uri        string         `db:"uri" json:"uri"`
	Header     sql.NullString `db:"header" json:"header"`
	PluginName string         `db:"plugin_name" json:"plugin_name"`
	Uuid       sql.NullString `db:"uuid" json:"uuid"`
	CreatedAt  sql.NullTime   `db:"created_at" json:"created_at"`
	UpdatedAt  sql.NullTime   `db:"updated_at" json:"updated_at"`
}

type GoadminOperationLog struct {
	ID        uint32       `db:"id" json:"id"`
	UserID    uint32       `db:"user_id" json:"user_id"`
	Path      string       `db:"path" json:"path"`
	Method    string       `db:"method" json:"method"`
	Ip        string       `db:"ip" json:"ip"`
	Input     string       `db:"input" json:"input"`
	CreatedAt sql.NullTime `db:"created_at" json:"created_at"`
	UpdatedAt sql.NullTime `db:"updated_at" json:"updated_at"`
}

type GoadminPermission struct {
	ID         uint32         `db:"id" json:"id"`
	Name       string         `db:"name" json:"name"`
	Slug       string         `db:"slug" json:"slug"`
	HttpMethod sql.NullString `db:"http_method" json:"http_method"`
	HttpPath   string         `db:"http_path" json:"http_path"`
	CreatedAt  sql.NullTime   `db:"created_at" json:"created_at"`
	UpdatedAt  sql.NullTime   `db:"updated_at" json:"updated_at"`
}

type GoadminRole struct {
	ID        uint32       `db:"id" json:"id"`
	Name      string       `db:"name" json:"name"`
	Slug      string       `db:"slug" json:"slug"`
	CreatedAt sql.NullTime `db:"created_at" json:"created_at"`
	UpdatedAt sql.NullTime `db:"updated_at" json:"updated_at"`
}

type GoadminRoleMenu struct {
	RoleID    uint32       `db:"role_id" json:"role_id"`
	MenuID    uint32       `db:"menu_id" json:"menu_id"`
	CreatedAt sql.NullTime `db:"created_at" json:"created_at"`
	UpdatedAt sql.NullTime `db:"updated_at" json:"updated_at"`
}

type GoadminRolePermission struct {
	RoleID       uint32       `db:"role_id" json:"role_id"`
	PermissionID uint32       `db:"permission_id" json:"permission_id"`
	CreatedAt    sql.NullTime `db:"created_at" json:"created_at"`
	UpdatedAt    sql.NullTime `db:"updated_at" json:"updated_at"`
}

type GoadminRoleUser struct {
	RoleID    uint32       `db:"role_id" json:"role_id"`
	UserID    uint32       `db:"user_id" json:"user_id"`
	CreatedAt sql.NullTime `db:"created_at" json:"created_at"`
	UpdatedAt sql.NullTime `db:"updated_at" json:"updated_at"`
}

type GoadminSession struct {
	ID        uint32       `db:"id" json:"id"`
	Sid       string       `db:"sid" json:"sid"`
	Values    string       `db:"values" json:"values"`
	CreatedAt sql.NullTime `db:"created_at" json:"created_at"`
	UpdatedAt sql.NullTime `db:"updated_at" json:"updated_at"`
}

type GoadminSite struct {
	ID          uint32         `db:"id" json:"id"`
	Key         sql.NullString `db:"key" json:"key"`
	Value       sql.NullString `db:"value" json:"value"`
	Description sql.NullString `db:"description" json:"description"`
	State       uint32         `db:"state" json:"state"`
	CreatedAt   sql.NullTime   `db:"created_at" json:"created_at"`
	UpdatedAt   sql.NullTime   `db:"updated_at" json:"updated_at"`
}

type GoadminUser struct {
	ID            uint32         `db:"id" json:"id"`
	Username      string         `db:"username" json:"username"`
	Password      string         `db:"password" json:"password"`
	Name          string         `db:"name" json:"name"`
	Avatar        sql.NullString `db:"avatar" json:"avatar"`
	RememberToken sql.NullString `db:"remember_token" json:"remember_token"`
	CreatedAt     sql.NullTime   `db:"created_at" json:"created_at"`
	UpdatedAt     sql.NullTime   `db:"updated_at" json:"updated_at"`
	Email         string         `db:"email" json:"email"`
}

type GoadminUserPermission struct {
	UserID       uint32       `db:"user_id" json:"user_id"`
	PermissionID uint32       `db:"permission_id" json:"permission_id"`
	CreatedAt    sql.NullTime `db:"created_at" json:"created_at"`
	UpdatedAt    sql.NullTime `db:"updated_at" json:"updated_at"`
}
